# Generated by Django 3.1.3 on 2020-11-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KrxStockListig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('symbol', models.CharField(max_length=256)),
                ('sector', models.CharField(max_length=256)),
                ('industry', models.CharField(max_length=256)),
                ('listing_day', models.DateField()),
                ('settle_month', models.DateField()),
                ('representative', models.CharField(max_length=256)),
                ('homepage', models.CharField(max_length=2048)),
                ('region', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'krx_listing',
            },
        ),
        migrations.CreateModel(
            name='NaverBusinessDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_day', models.DateField()),
            ],
            options={
                'db_table': 'business_day',
            },
        ),
    ]
