# Generated by Django 3.1.3 on 2020-11-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upbit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upbitdaycandle',
            options={'verbose_name': 'Upbit Day Candle'},
        ),
        migrations.AlterModelOptions(
            name='upbitmarket',
            options={'verbose_name': 'Upbit Market'},
        ),
        migrations.AlterModelOptions(
            name='upbitminutecandle',
            options={'verbose_name': 'Upbit Minute Candle'},
        ),
        migrations.AlterModelOptions(
            name='upbitmonthcandle',
            options={'verbose_name': 'Upbit Month Candle'},
        ),
        migrations.AlterModelOptions(
            name='upbitticker',
            options={'verbose_name': 'Upbit Ticker'},
        ),
        migrations.AlterModelOptions(
            name='upbitticks',
            options={'verbose_name': 'Upbit Tick'},
        ),
        migrations.AlterModelOptions(
            name='upbitweekcandle',
            options={'verbose_name': 'Upbit Week Candle'},
        ),
        migrations.AlterModelTable(
            name='upbitdaycandle',
            table='Upbit Day Candle Data',
        ),
        migrations.AlterModelTable(
            name='upbitmarket',
            table='Upbit Market Data',
        ),
        migrations.AlterModelTable(
            name='upbitminutecandle',
            table='Upbit Minute Candle Data',
        ),
        migrations.AlterModelTable(
            name='upbitmonthcandle',
            table='Upbit Month Candle Data',
        ),
        migrations.AlterModelTable(
            name='upbitticker',
            table='Upbit Ticker Data',
        ),
        migrations.AlterModelTable(
            name='upbitweekcandle',
            table='Upbit Week Candle Data',
        ),
    ]
