# Generated by Django 3.1.3 on 2020-11-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KRXListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16)),
                ('market', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('sector', models.CharField(max_length=128)),
                ('industry', models.CharField(max_length=128)),
                ('listingDate', models.DateField()),
                ('settleMonth', models.CharField(max_length=8)),
                ('representative', models.CharField(max_length=64)),
                ('homepage', models.CharField(max_length=512)),
                ('region', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'KRX Listing',
            },
        ),
    ]
